### ISSUE TITLE
Images from recent chapters are displayed incorrectly (PATH: /lastest)

### ISSUE THREAD

**Issue by jeluchu** [carlos-burelo/monoschinos-api-v2#3]
In the recent episodes section, the corresponding image of the series was previously shown for each episode. Now for some reason a black image is displayed with the following url: https://monoschinos2.com/public/img/capblank.png

Could it be that MonosChinos has changed something in their code again that the API is not fetching correctly?

**Comment by carlos-burelo** [comment]
Hello friend, I have already been reviewing the page a bit and I have already found the solution to the problem, indeed, the DOM elements have been reorganized, but this is a very small change so I wanted to ask you if the problem is present in other places for make a general fix :D

**Comment by jeluchu** [comment]
Sorry I just saw it, I'll check and if I see it on more sites I'll let you know @carlos-burelo
