### ISSUE TITLE
Problems loading series information and episode lists (PATH: /anime/:id)

### ISSUE THREAD

**Issue by jeluchu** [carlos-burelo/monoschinos-api-v2#4]
**Request and Response** according to documentation

> PATH: /anime/:id

|Querys|Params|
|-|-|
|none|`id`|

```
{
  "banner": "https://monoschinos2.com/assets/img/serie/portada/Wano_Country_Arc.png",
  "image": "https://monoschinos2.com/thumbs/imagen/juanitowano.jpg?v=1",
  "title": "One Piece",
  "sinopsis": "Una historia épica de piratas, donde narra la historia de \"Monkey D. Luffy\" quien cuando tenia 7 años, comió accidentalmente una \"Akuma no mi\"(Fruta del diablo) la cual le convirtió en un hombre de goma. Por otra parte \"Gol D. Roger\" conocido com... Ver más",
  "status": "Estreno",
  "date": 1999,
  "rating": "4.7",
  "genders": [
    "Acción",
    "Aventura",
    "Comedia",
    "Drama",
    "Fantasía",
    "Shonen"
  ],
  "episodes": [
    {
      "image": "https://monoschinos2.com/public/img/default.gif",
      "no": 1,
      "id": "one-piece-episodio-1"
    },
    {
      "image": "https://monoschinos2.com/public/img/default.gif",
      "no": 2,
      "id": "one-piece-episodio-2"
    }
    { ... }
  ]
}
```

I have been seeing that in many series the information is not loading correctly, and along with that the episode list is not loading correctly either, here I show you the 2 errors that I have found when making queries to some animes

> Error 1

> http://localhost:5000/anime/blade-runner-black-lotus-sub-espanol
> https://monoschinos2.com/anime/blade-runner-black-lotus-sub-espanol

```
{
  "id": "intertal-server-error",
  "message": "Cannot read properties of null (reading '0')"
}
```

> Error 2

> http://localhost:5000/anime/shigatsu-wa-kimi-no-uso-sub-espanol
> https://monoschinos2.com/anime/shigatsu-wa-kimi-no-uso-sub-espanol

```
{
  "id": "intertal-server-error",
  "message": "Cannot read property '0' of null"
}
```

**Comment by carlos-burelo** [comment]
Honestly, I'm glad that the page is actively updating its content, but as the DOM elements change I don't know when they will stop hahaha, in a moment I fix it, lately my IP address has been affected by CloudFlare and practically any request gives me status 403, so I will need you to confirm if the change was really made correctly because I practically do it just to see if I really get the data XD

**Comment by carlos-burelo** [comment]
Problem solved, I will leave the issue open in case any other problem related to the same route (/anime/:id) arises 😀

**Comment by carlos-burelo** [comment]
If any other problem arises, do not hesitate to contact me via telegram, github does not always notify me when a new issue comes out
